language: python

python:
  - "3.5"
  - "3.6"

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS blog_test;" -uroot

install:
  - pip install -r requirements.txt

script:
  - coverage run --source=apps manage.py test apps

after_success:
  - coverage report
  - coveralls
